/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import BusinessObjects.SocioLocal;
import BusinessObjects.SociosBusiness;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 54234
 */
public class Prestamo extends javax.swing.JFrame {

    private JDateChooser dateChooser;
    Date fechaLocal;

    /**
     * Creates new form MenuPrincipal
     */
    public Prestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        campDni = new javax.swing.JTextField();
        botonId = new javax.swing.JRadioButton();
        botonDni = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        campIdentificacion = new javax.swing.JTextField();
        botonPrestar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        botonCalendario = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel2.setText("INGRESE DNI O ID DEL SOCIO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel4.setText(">");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 10, 30));

        jToggleButton1.setBackground(new java.awt.Color(217, 217, 217));
        jToggleButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jToggleButton1.setText("MENU");
        jToggleButton1.setBorder(null);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("PRESTAMO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 30));
        jPanel1.add(campDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 40));

        buttonGroup1.add(botonId);
        botonId.setText("ID");
        jPanel1.add(botonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        buttonGroup1.add(botonDni);
        botonDni.setText("DNI");
        jPanel1.add(botonDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel7.setText("FECHA DE DEVOLUCIÓN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 170, 30));
        jPanel1.add(campIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 40));

        botonPrestar.setBackground(new java.awt.Color(204, 255, 204));
        botonPrestar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonPrestar.setText("PRESTAR");
        botonPrestar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPrestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestarActionPerformed(evt);
            }
        });
        jPanel1.add(botonPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 90, 40));

        jLabel16.setFont(new java.awt.Font("Edwardian Script ITC", 1, 200)); // NOI18N
        jLabel16.setText("B");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 260, 190));

        jLabel17.setFont(new java.awt.Font("Edwardian Script ITC", 1, 200)); // NOI18N
        jLabel17.setText("F");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 260, 190));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel8.setText("INGRESE NUMERO DE IDENTIFICACIÓN DEL LIBRO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 30));

        labelFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 150, 30));

        botonCalendario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCalendario.setText("Calendario");
        botonCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        FONDO.setText("jLabel1");
        jPanel1.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void botonPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestarActionPerformed
        String texto;
        String texto1;
        SociosBusiness socio = new SociosBusiness();
        if (botonId.isSelected()) {
            try {
                //obtengo los numeros de los campos de textos
                texto = campDni.getText();

                // Convierto el texto a int
                int id = Integer.parseInt(texto);
                boolean respuesta = socio.existeSocioID(id);
                if (respuesta) {
                    SocioLocal local = SocioLocal.getInstance();
                    local.setId(id);
                    ModificarDatos datos = new ModificarDatos();
                    datos.setVisible(true);
                    this.dispose();
                } else if (!respuesta) {
                    JOptionPane.showMessageDialog(null, "socio no encontrado");
                }

            } catch (NumberFormatException e) {
                // Manejar el error si el texto no es un número válido
                JOptionPane.showMessageDialog(null, "ingrese un numero valido");
            }
        }
        //Obtener lista de socios

    }//GEN-LAST:event_botonPrestarActionPerformed

    private void botonCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalendarioActionPerformed
        // Crear e invocar el diálogo
        FechaNacimientoDialog dialog = new FechaNacimientoDialog(Prestamo.this);
        dialog.setVisible(true);  // Al ser modal, el programa se "pausa" aquí hasta que se cierre el diálogo

        // Actualizar la variable fechaNacimiento después de cerrar el diálogo
        fechaLocal = dialog.getFechaNacimiento();

        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");  // Formato deseado
        labelFecha.setText(formato.format(fechaLocal));// convierto el Date en String        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalendarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton botonCalendario;
    private javax.swing.JRadioButton botonDni;
    private javax.swing.JRadioButton botonId;
    private javax.swing.JButton botonPrestar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campDni;
    private javax.swing.JTextField campIdentificacion;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelFecha;
    // End of variables declaration//GEN-END:variables
}
